name: typecheck all things
on:
  push:
    branches: ['main']
jobs:
  check:
    name: Check Everything
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    env:
        AGDA_VERSION: 2.8.0.2
        AGDA_SHA256: 2bcf24bb561b1be859bba841e5d67962d1616b3251bc147f878e4f60a2fbd9f7
        STDLIB_COMMIT: 2a5a0dec0a3cb5c87468ce101388a513d39dbf10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1
        with:
          repository: agda/agda-stdlib
          ref: ${{ env.STDLIB_COMMIT }}
          path: .ci/agda-stdlib

      - name: Install Agda
        run: |
          curl -sfLo agda.tar.xz "https://github.com/agda/agda/releases/download/v${AGDA_VERSION}/Agda-v${AGDA_VERSION}-linux.tar.xz"
          echo "${AGDA_SHA256}  agda.tar.xz" | sha256sum -c -
          mkdir -p "$HOME/.local/bin"
          tar xJf agda.tar.xz -C "$HOME/.local/bin"
          rm agda.tar.xz
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Register agda-stdlib
        run: |
          mkdir -p ~/.agda
          echo "$GITHUB_WORKSPACE/.ci/agda-stdlib/standard-library.agda-lib" > ~/.agda/libraries
          echo standard-library > ~/.agda/defaults

      - run: agda --version && ./runall.sh
